x-superset-image: &superset-image apache/superset:latest-dev
x-superset-depends-on: &superset-depends-on
  - qos_superset_db
  - qos_superset_redis
x-superset-volumes: &superset-volumes
  - ./docker:/app/docker
  - superset_home:/app/superset_home

version: "3.7"

services:
  qos_superset_redis:
    image: redis:latest
    container_name: qos_superset_redis
    restart: always
    volumes:
      - redis:/data

  qos_superset_db:
    env_file: docker/.env
    image: postgres:10
    container_name: qos_superset_db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_home:/var/lib/postgresql/data

  qos_superset_app:
    env_file: docker/.env-non-dev
    image: *superset-image
    container_name: qos_superset_app
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    user: "root"
    restart: always
    ports:
      - 8088:8088
    depends_on: *superset-depends-on
    volumes: *superset-volumes

  qos_superset_init:
    image: *superset-image
    container_name: qos_superset_init
    command: ["/app/docker/docker-init.sh"]
    env_file: docker/.env-non-dev
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes

  # qos_superset_worker:
  #   image: *superset-image
  #   container_name: qos_superset_worker
  #   command: ["/app/docker/docker-bootstrap.sh", "worker"]
  #   env_file: docker/.env-non-dev
  #   restart: always
  #   depends_on: *superset-depends-on
  #   user: "root"
  #   volumes: *superset-volumes

  # qos_superset_worker_beat:
  #   image: *superset-image
  #   container_name: qos_superset_worker_beat
  #   command: ["/app/docker/docker-bootstrap.sh", "beat"]
  #   env_file: docker/.env-non-dev
  #   restart: always
  #   depends_on: *superset-depends-on
  #   user: "root"
  #   volumes: *superset-volumes

volumes:
  superset_home:
    external: false
  db_home:
    external: false
  redis:
    external: false
